package model;

import java.time.LocalDate;
import java.time.temporal.ChronoUnit;

/**
 * Transaction - Records a borrow/return event for a specific book and user.
 *
 * OOP Concepts:
 *   - Encapsulation : all fields are private
 *   - Abstraction   : fine calculation logic hidden inside calculateFine()
 *
 * Fine Policy:
 *   - Borrow period : 14 days
 *   - Fine rate     : Rs. 5 per day after due date
 */
public class Transaction {

    /** Fine charged per overdue day in rupees. */
    public static final double FINE_PER_DAY   = 5.0;

    /** Maximum allowed borrow duration in days. */
    public static final int    BORROW_DAYS    = 14;

    // ─── Fields ────────────────────────────────────────────────────────────────
    private int        transactionId;  // Auto-generated by DB
    private String     bookId;         // FK → books.book_id
    private int        userId;         // FK → users.user_id
    private LocalDate  borrowDate;     // Date book was borrowed
    private LocalDate  dueDate;        // borrowDate + 14 days
    private LocalDate  returnDate;     // Null until returned
    private double     fineAmount;     // Calculated fine (0 if returned on time)
    private String     status;         // "BORROWED" or "RETURNED"

    // ─── Constructors ──────────────────────────────────────────────────────────

    /** Default constructor. */
    public Transaction() {}

    /**
     * Constructor for a new borrow event.
     * Due date is automatically set to borrowDate + BORROW_DAYS.
     *
     * @param bookId    the book being borrowed
     * @param userId    the user borrowing the book
     * @param borrowDate date of borrowing
     */
    public Transaction(String bookId, int userId, LocalDate borrowDate) {
        this.bookId     = bookId;
        this.userId     = userId;
        this.borrowDate = borrowDate;
        this.dueDate    = borrowDate.plusDays(BORROW_DAYS);
        this.returnDate = null;
        this.fineAmount = 0.0;
        this.status     = "BORROWED";
    }

    /**
     * Full constructor — used when loading a transaction from the database.
     */
    public Transaction(int transactionId, String bookId, int userId,
                       LocalDate borrowDate, LocalDate dueDate,
                       LocalDate returnDate, double fineAmount, String status) {
        this.transactionId = transactionId;
        this.bookId        = bookId;
        this.userId        = userId;
        this.borrowDate    = borrowDate;
        this.dueDate       = dueDate;
        this.returnDate    = returnDate;
        this.fineAmount    = fineAmount;
        this.status        = status;
    }

    // ─── Business Logic ────────────────────────────────────────────────────────

    /**
     * Calculates the fine for a given return date.
     * Fine = overdue days × FINE_PER_DAY
     *
     * @param  returnDate the actual date the book is returned
     * @return fine amount in rupees (0 if returned on or before due date)
     */
    public double calculateFine(LocalDate returnDate) {
        if (returnDate.isAfter(dueDate)) {
            long overdueDays = ChronoUnit.DAYS.between(dueDate, returnDate);
            return overdueDays * FINE_PER_DAY;
        }
        return 0.0;
    }

    /**
     * Returns the number of days this transaction is currently overdue.
     * Uses today's date if not yet returned.
     *
     * @return days overdue (0 if not overdue)
     */
    public long getOverdueDays() {
        LocalDate checkDate = (returnDate != null) ? returnDate : LocalDate.now();
        if (checkDate.isAfter(dueDate)) {
            return ChronoUnit.DAYS.between(dueDate, checkDate);
        }
        return 0;
    }

    /** Returns true if the book is currently overdue. */
    public boolean isOverdue() {
        return getOverdueDays() > 0 && "BORROWED".equals(status);
    }

    // ─── Getters ───────────────────────────────────────────────────────────────

    public int       getTransactionId() { return transactionId; }
    public String    getBookId()        { return bookId;        }
    public int       getUserId()        { return userId;        }
    public LocalDate getBorrowDate()    { return borrowDate;    }
    public LocalDate getDueDate()       { return dueDate;       }
    public LocalDate getReturnDate()    { return returnDate;    }
    public double    getFineAmount()    { return fineAmount;    }
    public String    getStatus()        { return status;        }

    // ─── Setters ───────────────────────────────────────────────────────────────

    public void setTransactionId(int id)        { this.transactionId = id;         }
    public void setBookId(String bookId)        { this.bookId        = bookId;     }
    public void setUserId(int userId)           { this.userId        = userId;     }
    public void setBorrowDate(LocalDate d)      { this.borrowDate    = d;          }
    public void setDueDate(LocalDate d)         { this.dueDate       = d;          }
    public void setReturnDate(LocalDate d)      { this.returnDate    = d;          }
    public void setFineAmount(double fine)      { this.fineAmount    = fine;       }
    public void setStatus(String status)        { this.status        = status;     }

    // ─── toString ──────────────────────────────────────────────────────────────

    @Override
    public String toString() {
        String retDateStr = (returnDate != null) ? returnDate.toString() : "Not Returned";
        return String.format(
            "| %-4d | %-6s | %-4d | %-12s | %-12s | %-12s | Rs.%-7.2f | %-9s |",
            transactionId, bookId, userId, borrowDate, dueDate, retDateStr, fineAmount, status
        );
    }
}
